---
title: "saros TODO"
author: "Stephan Daus"
output: 
  html_document: 
    toc: yes
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Version 1.0
1   plot_html comes twice instead of one html and one pdf
x   No bivariates at all for s_303 or s_30w (in SSN)
x   s_303w_8_fct_sentind3d_kom_BY_sentind3d_kom
1   obj_name: .variable_name_indep shows as NA for univariates (still)



1   Avoid sorting first on .element_name and then indep


3   Clean up the obj_name and filename_prefix stuff.
1   Løse skript for stolpediagrammer, kart (signifikante forskjeller på fylke/landsdel/kommune), tabeller
1   Trivariater: landsdel X resp, skolestørrelse X resp, kommune størrelse X resp osv.
3   Construct a global list of filename_prefixes. If it is already there, add "_2"
3   Avoid running remove_non_significant_bivariates if already excepted

3   Prettier duplicated labels warning, containing variable name, bullet points/new line.
3   Better checks of input data: Provide feedback/log on not mentioned variables, included variables, excluded due to non-significance, 
1   mesos: why fails if data.frame but works with tibble??
2   mesos: Keep sorting of variables in plots equal across target and others. (but will likely change this type of plot anyway)
1   Call summary_data only once in gen_element_and_qmd_snippet3
1   Move common procedures in the dataprep scripts into saros to avoid accidental issues
        mesos_var => must droplevels()
        trim and sanitize factor labels
        stop if not all used variables have a label (can be turned off)
        across(where(~is.factor(.x)), ~forcats::fct_relabel(.x, function(x) na_if(x, ""))),
             across(where(~is.character(.x)), ~na_if(.x, ""))
3   Multiple authors in a chapter_overview cell should be expanded in any YAML: process_yaml.
2   Always ignore author column for Mesos
3   Redesign entire refine_chapter_overview, remove_non_significant_bivariates and sigtest
2   Also export a complete archivable dataset with codebook
        en side med lenker til følgende:
        Datasettet
        En kodebok med variabelnavn, variabel-label, unike verdier, antall missing, data-type)
            Excel, HTML
        Eventuelle maler vi kommer på senere for dokumentasjon.
3   Faster read_main_password_file
        vectorize   lapply(usernames, FUN = function(user) {
    passwd <- master_table[master_table$username == user, "password"]
1   No bivariates?
2   Merge and refactor the relabelling functions (qualtrics, stata, SX, etc)
3   Introduce {targets}, but figure out the R-quarto-render (_freeze) setup
        Must be able to run a new report without rerunning everything.
3   setup_access_restrictions rel_path_base_to_parent_of_user_restricted_folder should give warning if NULL (not error)

# nifutemplate
2   SSN_methodchapter_inlines.R and SSN_methodchapter.qmd
        Turn method chapter into a more generic function?
1   functions to quickly download template files to a folder?


# Chapter overview
1   not keeping significant relationships! Seems all or nothing?
3   cli_inform: rows removed with hide_bi_entry_if_sig_above

# Structure
2   single_y_bivariate_elements: if TRUE, then each bivariate will contain only a single y variable, and one x variable, rather than entire batteries.

# saros.structure
1   data folder structure (in saros.structure)
2   Rproj must disable RData saving/use and Rhistory: set up for multiple users
3   functions to simplify copying of files
    in saros.structure
    in nifutheme (resources)
3   target and renv initialization with menu selection. =\> {saros.template}

# Internals
4   Can find_test be combined with find_stat_config?
2   Methodize
        Input validation functions
        Reduce number of arguments
        tryCatch() for file saving
        match(.x, data_cols) => What to do if nothing is found?
3   Remove rlang::exec when calling own functions that take rlang::list2()
2   No variable label will cause text-output (interpretations) to use NA.
    2   Review all stringi::stri_c( and check whether there is a possibility of inputs being NA. Should then use stringi::stri_remove_empty_na( before
    2   Any organize_by set of variables in chapter_overview should not have NA (or deal appropriately with them)
3    Warning in value[[3L]](cond) :                            
  cli progress bar update failed: subscript out of bounds
      Only for mesos reports.
3   Warning messages:
        In (function (case_insensitive = FALSE, overlap = FALSE,  ... :
          Unknown option to `stri_opts_fixed`.

## Reverse engineering from Word to Quarto
2   Test replace_docx_imgs_with_mscharts
3   reformat_qmd_from_docx_copy() og split_qmd_to_chapters()
        Sjekk slides

# Documentation (all written such that slides become easy to produce):

2   for_editor article
2   for_chapter_author article
2   for_data_cleaner article
        guidelines for variable names, labels, etc
            stick to english whenever possible. underscore to distinguish levels
            avoid years (a survey may cross a year, be published later, etc)
            use cycle-numbering, cohort, etc which are more stable
2   for_end_user article
3   Flytte TODO til Github issues...


# Sigtest
2   warning: n min(table(data[, c(dep_pos, indep_pos)])) :
  no non-missing arguments to min; returning Inf
    Why would data be empty?
2 Strange error without trace:
    Error in sample.int(length(x), size, replace, prob) : 
  NA in probability vector
1   no pval is showing!
    hide_sigtest_if_n_below seems too strict?
    Hide entire table if nothing to display?
3   overkill with main_question in label + as label-column header
3   variable	.variable_label	test	stat	p
        - Have some translations-headers?

# mesos
2   Option to specify what is used for tabset: c("element", "mesos_var", "dep") 

# plots
2   gglikert()
2   kontinuerlig avhengig => histogram
2   kontinuerlig avhengig x kategorisk uavhengig => boxplot
2   kontinuerlig avhengig x kontinuerlig uavhengig => scatter plot
2   Also, a lighter inactive shadow alpha. 
3   La brukerne selv sortere etter sin egen preferanse
-   tri_catcatcat_plot (z)
    -   Spørringene: resp x Ys - KU: fagfelt og institusjon x Ys - AGU: sektor x Ys.

2   estimate_plot_height: consider totals=TRUE
3   Make download button persistent by replacing opacity: 1; in JS class="ggiraph-toolbar ggiraph-toolbar-top"
3   colour_2nd_binary_cat is not working consistently with data\$s_43 (gender) and when mesos - legend is missing when there are two categories in cat_prop, but n

-   unused levels seem to cause confusion in hide_legend and colours. and tables
3   N in legend for each by group
4   prep_cat_prop_plot_pdf: Implement N= in labels when tooltips are unavailable
4   add_n_to_bygroup as arg
-   implement uni_plot_int_ bi_plot_intint_ bi_plot_intcat_

# tables
3   La brukerne selv sortere etter sin egen preferanse
3   For tabeller for det samme så tenker jeg prosent missing, snitt, SD, og antall outliers som default.* samt brutt ned på kategorisk uavhengig ved behov. *Men her skal man kunne sette bestilling på forhånd før rapport genereres.


# Colours
-2   Konsekvent fargepalett på tvers av figurer med samme svarskala
-1   Sikre at nifutheme fungerer manuelt

4   if .categories %in% names(colour_palette), use associated colour
    -   Bruk så fargepalett på resten
4   separate colour_palette for different needs: chapter, designated_type, .variable_role, ... 
4 allow paletter package functions (function fabrics)
      -   if is.colour =\> as colours, else if in paletter list, use that
      -   if colour_2nd_binary is applicable, should forcats::fct_rev(.x)
4   can label_font_size, main_font_size, font_family, data_label_decimal_symbol be set later through CSS/YAML?

# summarize_data

4   sorting of indep should only occur if is.ordered(data[[by_name]]), otherwise ignore it and just sort by .sum_value
4   only call summarize_data once and reuse.


# Arguments
3   Parallellism = c("none", "chapter", "inner")
     lapply_function <- if(require("future.apply)) future.lapply::future_lapply else lapply

4   distinguish between qmd_start/end for chapter.qmd, index.qmd and report.qmd?
4   move some parameters from \_report_generation_setup.yml to \_quarto.yml file and perform modifications in a R-script loaded in the beginning of index.qmd
    -   decimal marker?
    -   colour_palette?
3   descend is currently global across all variables...
3   Sjekk ut hypothes-is muligheter, skru av, moderator, osv.


# Folder structure

4   Separate subfolders in saros-output for PNG, DOCX (grraphs), TXT, XLSX
    - could use extension as input to function that saves, which adds folder name and extension

# tables

2   tri_catcatcat_table
3   vertical argument in tables provides a pivot-string similar to SSB: 1,2,3
    -   As any element_type so one can get all at once. OR, let reader decide?


# sarosverse structure

-   sarosverse imports:
    -   saros.base
    -   saros.docx 
        -   pkgs: officer, mschart, flextable
    -   saros.html 
        -   pkgs: gt, ggplot2, ggiraph, scales, ggfittext?
    -   saros.modelsig: 
        -   pkgs: infer
    -   saros.struct
        -   create__headers_file create_htaccess_file etc copy_dirs copy_from_themepackage
        -   initialize_project_structure (+ Rstudio project template)
    -   saros.text
        -   pkgs: openai, 
    -   saros.psych
        -   pkgs: psych, tidySEM, lavaan, tidySEM,
    -   saros.effect
    -   saros.qual
        -   new qualitative analysis package
    -   saros.graphic
    -   saros.utils
        -   pkgs: clipr
    
# cat_text

-   incorrect numbers?
-   If only single question, simplify output!
-   respecting data_label
-   long batteries not respecting n_top_bottom?
-   must explain that it is sum of upper categories
-   bool: str_to_sentence, asis

# saros.publish

2   automate creation of hashed passwords
4   automate copying of .htaccess and .htpasswd files to subfolders

# Raise issues in other packages
1   RStudio Quarto: Copying table from Word into Visual editor results in empty cols and rows
1   RStudio Quarto: Copying figure from Word into Visual editor results in image not found
1   Quarto-CLI: Seems that if the _nifu_global.yaml contains wrong paths (which?), we get a TypeError instead of an informative error. Could also be the main vs Main spelling for the render: 

4   Issue at <https://github.com/tidymodels/infer> about annoying warning.
4   Issue at Quarto-cli for: If processing fails, it leaves a temporary .rmarkdown file which if not manually deleted will cause the following error on the next rendering: "The name of the input file cannot contain the special shell characters: [ \<\>()\|:&;#?\*']"


# Version-naming system:
-   V1.0.0:   Cay G.
-   V1.1.0:   Siv-Elisabeth S.
-   V1.2.0:   Ann Cecilie 
-   V1.3.0:   Cathrine P.
-   V1.4.0:   Torstein de B


# Version 3.0

4   @keywords internal for all internal functions having documentation.
4   multiple levels of by (z-column in chapter_overview?)
4   If you return the same type of output from multiple functions, you should create a function that consistently creates exact the same format (to avoid accidental inconsistency), and consider making it an S3 class (so you can have a custom print method).
4   Generalize the element creator switch function and helper function so that user could create own element types. A function factory.
4   Replace separators with patterns? Or character vector patterns? First letters before numbers? Similar to the new splitters in {tidyr}
4   Tests for graphs using snapshots and data in ggplot object
4   Split off rename_variables into either janitor or a vctrs::vec_as_names() extension
4   Extract the atributes-setter function for the elements
    -   caption (element_name, .variable_label\_\*, mesos_group, )
    -   vanskelig ettersom create_caption krever data_out

# General improvements

-   speed performance
    +   early fails
    -   normalization with hash/ID lookup:
        -   chapter overview (input only)
        -   data frame (or string matrix?) of variables and their fixed information (labels, variable names, univariates?)
        -   data frame (or string matrix?) of bivariate combinations with sigtest info (long format)
        -   data frame (or numeric matrix?) of all summary_data stuff for univariates
        -   data frame (or numeric matrix?) of all summary_data stuff for bivariates
        -   NB: Matrices are hard to work with and do not allow grouping storage
        -   vectorization, avoid looping (can be parallellized in outer loop)
        -   profiling
        -   avoid copying
        -   vctrs, rlang, base
        -   premake summarized_data and reuse it across elements, filtering as needed
        -   pipe =\> no pipe
        -   if not grouping:
            -   dplyr::filter =\> vctrs::vec_slice()
            -   dplyr::mutate =\> base
            -   dplyr::select =\> base
            -   dplyr::pull =\> base
            -   bind_rows =\> vctrs::vec_rbind
            -   remove tidyselect/data masking: all using strings for columns names internally
            -   dtplyr?
-   refactoring
-   more memorable and logical naming of functions, arguments, etc.
-   rename files so they are logical for developers
    -   alphabetical order of operations
-   documentation and examples
    -   inheritParams
    -   exemplify all non-trivial argument inputs (lists, vectors, objects)
    -   better hints in error/warning messages
    -   progress bars
-   more robustness
    -   increase test coverage
    -   moduling / code refactoring
    -   target package / renv
    -   argument checks
-   flexible arguments
-   reduce size of package (in MB)
-   reduce dependencies
    -   find upstream packages
    -   copy code when applicable
    -   split functions into smaller and more robust packages
        -   analyze co-dependencies
-   simplify to reduce build/install time
    -   Examples, tests, data, inst-folder templates/attachments


############################################################## 

# OLD STUFF, IGNORE

## saros.instruments

```         
Improvement over time (p1-p0)
IRT parameters (a, b, c), with low discriminators, and extremely hard/easy items flagged
Items with responses above/below 95/5 percentage flagged
Low CFA loadings
Loadings improved if item removed
```

-   Make generalisert TIC, theta, item thresholds-grafmaker som tar mirt, MplusAutomation, lavaan, TAM, etc)

# Overall design

-   <https://github.com/tidymodels/model-implementation-principles/blob/master/06-arguments.Rmd>

# saros.model

## step_auto_tick_recode

-   Some form of automatic recode of multiple tick-box items where no cross is missing? Or perhaps strongly advice people not to use them?

## add_regression

-   Extract dummy recoder?
-   loading_cutoff =\> move to add_fit?
-   V2: How to distinguish x_var as single latent variable from set of manifest variables?
-   Improve extraction of errors in MplusAutomation::readModels(). New separate function: Extract variables that are failing

## run_model

## prepare_mplus_model

## extract_mplus_model

-   Make into broom tidier? Though will be of limited use.
-   cronbach, mcdonald_omega? Or using psych::alpha

## prepare_lavaan_model

# add_meaning

-   Incorporate all the below as glue strings.
-   latent_diff, construct_fit, effect, percent, univariate
-   instead of tolower, only change first letter of sentence.
-   V1: Template sentences for fit.
-   V2: Text reporting: Adding adverbial clauses to spice up: If contrast to previous finding.
-   V2: Text reporting: Summarize findings if all of the same regex (X positively correlated with all of Y1, Y2, Y3, ... and detailed=FALSE)
-   V2: Distinguish between first-time mention of a variable within a section (where full x_label is mentioned "Vi finner for x_label at...)
-   V2: What to do for the "else"-category, those not matched? Leave to user to specify a catch-all regex?
-   V2: Get someone to translate template sentences to English, German, Nynorsk, etc.

# add_rangeplot_chart, add_forest_chart, add_bivariate_chart

# omitted_recoder_df

-   return tibble if input tibble

-   keep labels

-   Scatter+trend line plots for linear/binary logistic regression models where x_focus is specified

-   Forest plot for regression model results



# create_psychometrics_report

-   Standard set with functions to conduct psychometric analysis. Summarizes models from various packages, and presents according to common objectives:
-   TODO: Should split into functions fitting into the tidymodelverse. This requires brooming TAM, mirt, CDM, sirt, lavaan, MplusAutomation, etc.
-   Aims:
-   single function to retrieve information on item-specific descriptives
-   single function to retrieve information on which items are likely worst fitting for unidimensional scale
-   single function to retrieve information comparing various models (uni, bi/multidimensional, correlated, second order, etc)

\*\* Versjon 0.3 \* Endre filnavnet \* argument: Velge hvilke funksjoner som skal kjøres \* argument: Velge hvilke IRT-modeller som skal kjøres (1PL, 2PL, etc) \* funksjon: Trekke ut Wright-map plot som egen funksjon (plot_1a) \* funksjon: Trekke ut ICC plots-loopen for TAM-data, som eegen funksjon \* funksjon: Trekke ut Mplus-modeller som egne funksjoner \* Generalisere mer (særlig grafer) og unngå hardkodede variabelnavn/labels \* Be Alexander Rorbitzh om å kunne endre navn på Plots-mappe \* argument: Endre argument defaults til engelsk/tom \* funksjon: Legge inn fortolkninger som tekst i fit (høy infit, etc). \* funksjon: Item information curves (all in one graph)

-   Bedre struktur på returnert objekt: alle rå-objekter i egen liste (raw). Input i egen liste (input), Alt nyttig i egen liste (\$summary)

-   summary\$mod: tibble, rader=modell, kolonner= person abilities mean, item spread, C alpha, CFA, TLI, RMSEA, SRMR, faktorladningsspredning,

-   summary\$tam_1pl: tibble, rader=item, kolonner=item difficulty, discrimination, outfit, infit, item information curve summary?,

-   funksjon: Excel-output av alt i \$summary-listen, inkl Chart-grafer?.

-   Lage/finne en oppskrift på hele valideringsprosessen, basere output rundt dette.

-   Legge inn flere pakker?

-   Mer om DIF/MI, local independence, Q3, etc

-   Bifaktor/second order-struktur?

-   Når andre pakker er oppdatert (ASCII), fjerne noen endringer av tittel, etc.?

-   Tidyselect?

-   Kontroller og Feilmeldinger (rlang)


# Gamle notater, kan være noen ideer verdt å beholde her

############################################################################# 

# NIFUstolper: Produksjon (direkte lagring til disk) av stolpediagrammer for spørsmålsbatterier gruppert etter supergrupper, grupper, osv og brutt ned på liste med brytningsvariabler

1 Unngå overskriving: Legg til siffer, sjekk på nytt, etc. 1 Algoritme for høyden (minste størrelse når strip-tekst går over flere linjer) 2 SVG eller vektorgrafikk i Word 2 facet-tekst justeres slik at den aldri forsvinner om den blir for mange linjer 2 Sjekk at det er færre verdier enn farger

# Produksjon av alle mulige tabeller for sett med variabler brutt ned på liste med brytningsvariabler, fordelt på batteri

1 function(. data, .outcome_vars=TIDY SELECT list.vars_break=NULL, .vars_break2=null, brytning_ved_rader=T, batteri_var="")

# Tekstgenerering av signifikanstester for sett med ordinale variabler brutt ned på liste med brytningsvariabler.

1 Fikse feil når det er flere grupper som sammenlignes (N og m= synes å være samme for 1. og 3. oppføring? 1 Lagre analysen per variableGroup - altså en ytterloop - kontinuerlig 1 Raskere, går tregt 2 Sortere gruppene etter faktor-levels, eller etter hva som er høyest. 1 Lagre krysstabeller i samme slengen. Setningen kan legges umiddelbart under tabellen. 2 Legge til totalen for å sammenligne gruppene med totalen, men er dette fortsatt uavhengige grupper? (add_total=T) 1 ta sjekk på om ordinalvariabel er ordered factor, gi informativ feilmelding 1 Sjekk om variabler inneholder NA, fjerne med advarsel 2 unngå coin-pakken, finne referanser til metoden (Agresti, 2007) 3 Hvilke grupper har høyest/lavest verdi, på hver variabel? 2 Andre ikke-parametriske distribusjoner (nominal-nominal, binær, interval, etc) 3 Omnibus-tester? 3 Ulike type fraser for ulike batterier (enten character vector of length 1 or character vector =length(unique(variableGroup) 3 Randomisere mellom fraser compareGroups-pakken? Bør også eksportere som CSV-fil resultatene da det kan være letter eå lese. "mer enig enn" kan da bli \> eller \<.

# NIFU_efa: EFA av alle utfallsvariabler

```         
Finner selv ut hvor mange faktorer er teoretisk mulige
Fjerner iterativt variabler med missing over 20%, forenkler variabler med mindre enn 10% per kategori 
en egen variabel i Structure forteller hvilke som skal snus i faktoranalyser
om ikke MplusAutomation oppdateres: kjører ESEM for å hente ut faktorladningene
Kobler på variableQuestion og variableGroup
Sorterer slik at sterkeste faktorladningene kommer først
Fjerner alt mellom -.4-.4 og omrokkerer faktorene
Printer ut i Excel, fargelegger
Legger ved rå (Spearman) korrelasjoner i eget regneark
```

# analyze_psych: Psykometriske analyser av konstrukter

```         
CFA for hvert spørsmålsbatteri og spørsmålsoverbatteri, m/alpha, CFA, TLI, RMSEA, SRMR, faktorladningsspredning, osv
Measurement invariance for hver av brytningsvariablene
Lager en samletabell for alle variableGroup
Optional item-nivå info, DIF, etc
```

Rapportere bug til Mplus om at \$1 blir kuttet vekk fra CI-output. Rapportere bug til MplusAutomation: LOGISTIC REGRESSION ODDS RATIO RESULTS kommer ikke med

# Tekstgenerering av Mplusmodeller

```         
Total, så hver spesifikk indirekte, innenfor disse vise deleffektene, så total indirekte, så direkte.
Benytter STDYX og STDY avhengig av type variabel
```

# Automatisk generering av hvert av det ovenstående for hvert batteri (samlefunksjon) i et Word-dokument med NIFU-template, gruppert etter headings,

3 Legger inn grafene, tabellene, signifikanstester, m.m. under korrekt overskrift. Må sortere riktig. Hm Må ha et register i CSV-fil eller lignende med fraser man kan benytte til variasjon, for introduksjon av grafer, tabeller, osv.
