---
author: Mark Twain
format: html
echo: false
editor: visual
---


```{r}
###  experimental docx-production
library(officer)
docx <- officer::read_docx()
```
# 3 Big mysteries


## How much do you like living in



::: {.content-visible when-format="html"}
```{r}
#| fig-cap: '_How much do you like living in_ (N = [100-100])'
uni_cat_prop_plot_html_x3_Big_mysteries_How_much_do_you_like_living_in <- 
  readRDS("3 Big mysteries/uni_cat_prop_plot_html/x3_Big_mysteries_How_much_do_you_like_living_in.rds")
ggiraph::girafe(ggobj = uni_cat_prop_plot_html_x3_Big_mysteries_How_much_do_you_like_living_in)
``` 

:::

Text




::: {.content-visible when-format="html"}
```{r}
#| fig-cap: '_How much do you like living in_ (N = [100-100])'
uni_cat_freq_plot_html_x3_Big_mysteries_How_much_do_you_like_living_in <- 
  readRDS("3 Big mysteries/uni_cat_freq_plot_html/x3_Big_mysteries_How_much_do_you_like_living_in.rds")
ggiraph::girafe(ggobj = uni_cat_freq_plot_html_x3_Big_mysteries_How_much_do_you_like_living_in)
``` 

:::

Text




::: {.content-visible when-format="html"}
```{r}
#| tbl-cap: ''
uni_cat_table_html_x3_Big_mysteries_How_much_do_you_like_living_in <- 
  readRDS("3 Big mysteries/uni_cat_table_html/x3_Big_mysteries_How_much_do_you_like_living_in.rds")
reactable::reactable(uni_cat_table_html_x3_Big_mysteries_How_much_do_you_like_living_in)
``` 

:::

Text




```{r}
uni_cat_sigtest_x3_Big_mysteries_How_much_do_you_like_living_in <- 
  readRDS("3 Big mysteries/uni_cat_sigtest/x3_Big_mysteries_How_much_do_you_like_living_in.rds")
reactable::reactable(uni_cat_sigtest_x3_Big_mysteries_How_much_do_you_like_living_in)
``` 









::: {.content-visible when-format="html"}
```{r}
#| fig-cap: '_How much do you like living in_  by x2_human(N = [100-100])'
bi_catcat_prop_plot_html_x3_Big_mysteries_How_much_do_you_like_living_in_BY_x2_human <- 
  readRDS("3 Big mysteries/bi_catcat_prop_plot_html/x3_Big_mysteries_How_much_do_you_like_living_in_BY_x2_human.rds")
ggiraph::girafe(ggobj = bi_catcat_prop_plot_html_x3_Big_mysteries_How_much_do_you_like_living_in_BY_x2_human)
``` 

:::

Text




::: {.content-visible when-format="html"}
```{r}
#| fig-cap: '_How much do you like living in_  by x2_human(N = [100-100])'
bi_catcat_freq_plot_html_x3_Big_mysteries_How_much_do_you_like_living_in_BY_x2_human <- 
  readRDS("3 Big mysteries/bi_catcat_freq_plot_html/x3_Big_mysteries_How_much_do_you_like_living_in_BY_x2_human.rds")
ggiraph::girafe(ggobj = bi_catcat_freq_plot_html_x3_Big_mysteries_How_much_do_you_like_living_in_BY_x2_human)
``` 

:::

Text




::: {.content-visible when-format="html"}
```{r}
#| tbl-cap: ''
bi_catcat_table_html_x3_Big_mysteries_How_much_do_you_like_living_in_BY_x2_human <- 
  readRDS("3 Big mysteries/bi_catcat_table_html/x3_Big_mysteries_How_much_do_you_like_living_in_BY_x2_human.rds")
reactable::reactable(bi_catcat_table_html_x3_Big_mysteries_How_much_do_you_like_living_in_BY_x2_human)
``` 

:::

Text




```{r}
bi_catcat_sigtest_x3_Big_mysteries_How_much_do_you_like_living_in_BY_x2_human <- 
  readRDS("3 Big mysteries/bi_catcat_sigtest/x3_Big_mysteries_How_much_do_you_like_living_in_BY_x2_human.rds")
reactable::reactable(bi_catcat_sigtest_x3_Big_mysteries_How_much_do_you_like_living_in_BY_x2_human)
``` 











## To what extent do you agree or disagree to the following policies



















```{r}
uni_int_sigtest_x3_Big_mysteries_To_what_extent_do_you_agree_or_disagree_to_the_following_policies <- 
  readRDS("3 Big mysteries/uni_int_sigtest/x3_Big_mysteries_To_what_extent_do_you_agree_or_disagree_to_the_following_policies.rds")
reactable::reactable(uni_int_sigtest_x3_Big_mysteries_To_what_extent_do_you_agree_or_disagree_to_the_following_policies)
``` 





















```{r}
bi_intcat_sigtest_x3_Big_mysteries_To_what_extent_do_you_agree_or_disagree_to_the_following_policies_BY_x2_human <- 
  readRDS("3 Big mysteries/bi_intcat_sigtest/x3_Big_mysteries_To_what_extent_do_you_agree_or_disagree_to_the_following_policies_BY_x2_human.rds")
reactable::reactable(bi_intcat_sigtest_x3_Big_mysteries_To_what_extent_do_you_agree_or_disagree_to_the_following_policies_BY_x2_human)
``` 







## Is respondent human?



::: {.content-visible when-format="html"}
```{r}
#| fig-cap: '_Is respondent human?_ (N = [100-100])'
uni_cat_prop_plot_html_x3_Big_mysteries_Is_respondent_human_ <- 
  readRDS("3 Big mysteries/uni_cat_prop_plot_html/x3_Big_mysteries_Is_respondent_human_.rds")
ggiraph::girafe(ggobj = uni_cat_prop_plot_html_x3_Big_mysteries_Is_respondent_human_)
``` 

:::

Text




::: {.content-visible when-format="html"}
```{r}
#| fig-cap: '_Is respondent human?_ (N = [100-100])'
uni_cat_freq_plot_html_x3_Big_mysteries_Is_respondent_human_ <- 
  readRDS("3 Big mysteries/uni_cat_freq_plot_html/x3_Big_mysteries_Is_respondent_human_.rds")
ggiraph::girafe(ggobj = uni_cat_freq_plot_html_x3_Big_mysteries_Is_respondent_human_)
``` 

:::

Text




::: {.content-visible when-format="html"}
```{r}
#| tbl-cap: ''
uni_cat_table_html_x3_Big_mysteries_Is_respondent_human_ <- 
  readRDS("3 Big mysteries/uni_cat_table_html/x3_Big_mysteries_Is_respondent_human_.rds")
reactable::reactable(uni_cat_table_html_x3_Big_mysteries_Is_respondent_human_)
``` 

:::

Text




```{r}
uni_cat_sigtest_x3_Big_mysteries_Is_respondent_human_ <- 
  readRDS("3 Big mysteries/uni_cat_sigtest/x3_Big_mysteries_Is_respondent_human_.rds")
reactable::reactable(uni_cat_sigtest_x3_Big_mysteries_Is_respondent_human_)
``` 
































```{r}
###  experimental docx-production
print(docx, target='3 Big mysteries.docx')
```